name: Build Package

runs-on: ubuntu-latest

steps:
  - uses: ./.github/workflows/templates/setup-node.yaml
  - run: npm ci
  - run: npm run build
  - uses: actions/upload-artifact@v4
    with:
      name: build
      path: dist/
