name: Publish to npm and GitHub Packages

runs-on: ubuntu-latest

steps:
  - uses: ./.github/workflows/templates/setup-node.yaml
  - name: Set up NPM for publishing
    run: |
      echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" >> .npmrc
      npm config set //registry.npmjs.org/:_authToken="${{ secrets.NPM_PAT }}"
  - name: Publish to npm
    run: npm publish --access public
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_PAT }}
  - name: Publish to GitHub Packages
    run: |
      echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" >> .npmrc
      npm publish
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}
