name: Build and release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [ published ]

jobs:
  test:
    uses: ./.github/workflows/templates/test.yaml

  build:
    uses: ./.github/workflows/templates/build.yaml
    needs: test

  release:
    uses: ./.github/workflows/templates/release.yaml
    needs: build

  publish:
    uses: ./.github/workflows/templates/publish.yaml
    needs: release
