name: Build and publish to npm and github

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

env:
  NODE_VERSION: "20"
  NPM_CACHE: "npm"
  DIST_PATH: "dist/"
  GH_PAT: ${{ secrets.GH_PAT }}
  NPM_PAT: ${{ secrets.NPM_PAT }}

jobs:
  setup:
    name: Setup Node.js and Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.NPM_CACHE }}

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and run tests
        run: |
          npm ci
          npm test

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js (Reused Step)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.NPM_CACHE }}
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ env.DIST_PATH }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Config git author
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
      - name: Bump version and tag
        id: version-bump
        run: |
          npx standard-version --release-as minor
          VERSION=$(jq -r .version package.json)
          echo "new_version=$VERSION" >> $GITHUB_ENV
      - name: Push changes
        run: |
          git pull --rebase origin main
          git push origin main --tags
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.new_version }}
          generated_notes: true

  publish:
    name: Publish to npm and GitHub Packages
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
      - name: Set up NPM for publishing
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" >> .npmrc
          npm config set //registry.npmjs.org/:_authToken="${{ secrets.NPM_PAT }}"
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PAT }}
      - name: Publish to GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" >> .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}
