name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [ published ]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: test

  release:
    uses: ./.github/workflows/release.yml
    needs: build

  publish:
    uses: ./.github/workflows/publish.yml
    needs: release